import type { Metadata } from "next";
import Header from "@/commonLayout/Header";
import Footer from "@/commonLayout/Footer";
import HeaderTwo from "@/commonLayout/HeaderTwo";
import FooterTwo from "@/commonLayout/FooterTwo";

export const metadata: Metadata = {
  title: "Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="">
      <HeaderTwo />
      {children}
      <FooterTwo />
    </main>
  );
}
