import hotel from "../public/dashboard/hotel.png";
import { CiCirclePlus } from "react-icons/ci";

export const data = [
  { title: "My Posted Jobs", icon: CiCirclePlus },
  { title: "Post Job", icon: "" },
  { title: "AI Tools", icon: "" },
  { title: "Appointments", icon: "" },
  { title: "Subscription Plan", icon: "" },
  { title: "Hire Employees", icon: "" },
  { title: "Shift Plan", icon: "" },
  { title: "Salary Calculator", icon: "" },
  { title: "WhatsApp Support", icon: "" },
  { title: "Add WhatsApp Link", icon: "" },
  { title: "Invoice & Payments", icon: "" },
  { title: "Contact & Support", icon: "" },
  { title: "Verify Account", icon: "" },
  { title: "Download Center", icon: "" },
];

export const postJobsDetails = [
  {
    image: hotel,
    company: "Sparktech Agency",
    location: "California, Usa",
    position: "Senior Business Analys",
    jobType: "Full Time",
    salary: "$200-$300/Month",
    postedTime: "2 Days Ago",
  },
  {
    image: hotel,
    company: "Sparktech Agency",
    location: "California, Usa",
    position: "Senior Business Analys",
    jobType: "Full Time",
    salary: "$200-$300/Month",
    postedTime: "2 Days Ago",
  },
  {
    image: hotel,
    company: "Sparktech Agency",
    location: "California, Usa",
    position: "Senior Business Analys",
    jobType: "Full Time",
    salary: "$200-$300/Month",
    postedTime: "2 Days Ago",
  },
  {
    image: hotel,
    company: "Sparktech Agency",
    location: "California, Usa",
    position: "Senior Business Analys",
    jobType: "Full Time",
    salary: "$200-$300/Month",
    postedTime: "2 Days Ago",
  },
  {
    image: hotel,
    company: "Sparktech Agency",
    location: "California, Usa",
    position: "Senior Business Analys",
    jobType: "Full Time",
    salary: "$200-$300/Month",
    postedTime: "2 Days Ago",
  },
  {
    image: hotel,
    company: "Sparktech Agency",
    location: "California, Usa",
    position: "Senior Business Analys",
    jobType: "Full Time",
    salary: "$200-$300/Month",
    postedTime: "2 Days Ago",
  },
  {
    image: hotel,
    company: "Sparktech Agency",
    location: "California, Usa",
    position: "Senior Business Analys",
    jobType: "Full Time",
    salary: "$200-$300/Month",
    postedTime: "2 Days Ago",
  },
];
